Repository SAKPaaS/backend, pull requests merged in 2020-05, with the labels that each got.

#153 TINF-327 Added userUuid field and another constructor for occupancy
  src/main/java/de/sakpaas/backend/model/Occupancy.java
Labels: enhancement

#152 TINF-352: Changed return types of favorites endpoint
  src/main/java/de/sakpaas/backend/v2/controller/UserController.java
Labels: enhancement

#155 TINF-333: Location Types Endpoint
  src/main/java/de/sakpaas/backend/service/LocationDetailsRepository.java
  src/main/java/de/sakpaas/backend/service/LocationService.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/test/java/de/sakpaas/backend/service/LocationDetailsRepositoryTest.java
  src/test/java/de/sakpaas/backend/v2/controller/LocationControllerTest.java
Labels: enhancement

#154 Bugfix/TINF-355: Code 400 & IllegalArgumentException
  src/main/java/de/sakpaas/backend/service/SearchMappingService.java
  src/test/java/de/sakpaas/backend/service/SearchMappingServiceTest.java
Labels: bug

#151 TINF-324: Integration Test
  pom.xml
  src/main/java/de/sakpaas/backend/service/UserService.java
  src/main/java/de/sakpaas/backend/v2/controller/UserController.java
  src/main/java/de/sakpaas/backend/v2/mapper/LocationMapper.java
  src/test/java/de/sakpaas/backend/HappyHamsterTest.java
  src/test/java/de/sakpaas/backend/IntegrationTest.java
  src/test/java/de/sakpaas/backend/controller/UserControllerTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointAddFavoriteByLocationIdTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointGetLocationByIdTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointGetLocationsByCoordinatesTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointListFavoritesTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointRemoveFavoriteByLocationIdTest.java
Labels: enhancement

#150 Bugfix/changes
  src/main/java/de/sakpaas/backend/service/SearchService.java
  src/test/java/de/sakpaas/backend/service/SearchServiceTest.java
Labels: bug

#159 TINF-364: Added Cors Header to User Controller
  src/main/java/de/sakpaas/backend/v2/controller/UserController.java
Labels: bug

#157 TINF-357: fixed Null-Pointer-Exception in SearchResultMapper
  src/main/java/de/sakpaas/backend/service/SearchService.java
Labels: bug

#156 TINF-361: throw Exception
  src/main/java/de/sakpaas/backend/exception/EmptySearchQueryException.java
  src/main/java/de/sakpaas/backend/service/SearchService.java
  src/test/java/de/sakpaas/backend/service/SearchServiceTest.java
Labels: bug

#164 TINF-368: Disable Keycloak for CORS Preflight-Requests
  src/main/resources/application.yml
Labels: bug

#161 TINF-329: Endpoint Test /v2/locations/{id}/occupancy
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointAddOccupancyTest.java
Labels: enhancement

#162 TINF-324: Endpoint Test /v2/locations/search/{query}
  src/main/java/de/sakpaas/backend/service/LocationDetailsRepository.java
  src/main/resources/sql/on_release.sql
  src/test/java/de/sakpaas/backend/IntegrationTest.java
  src/test/java/de/sakpaas/backend/service/LocationDetailsRepositoryTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointListLocationTypesTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointSearchLocationsTest.java
  src/test/java/de/sakpaas/backend/v2/controller/LocationControllerTest.java
Labels: enhancement

#166 added @Repository annotation
  src/main/java/de/sakpaas/backend/service/AddressRepository.java
  src/main/java/de/sakpaas/backend/service/FavoriteRepository.java
  src/main/java/de/sakpaas/backend/service/LocationDetailsRepository.java
  src/main/java/de/sakpaas/backend/service/LocationRepository.java
  src/main/java/de/sakpaas/backend/service/OccupancyRepository.java
  src/main/java/de/sakpaas/backend/service/PresenceRepository.java
Labels: enhancement

#168 TINF-397: RequestUtils.generateConnectionHash()
  src/main/java/de/sakpaas/backend/util/RequestUtils.java
  src/test/java/de/sakpaas/backend/util/RequestUtilsTest.java
Labels: enhancement

#167 TINF-393: Occupancy-Entity and OccupancyRepository REQUEST_HASH
  src/main/java/de/sakpaas/backend/model/Occupancy.java
  src/main/java/de/sakpaas/backend/service/OccupancyRepository.java
  src/main/java/de/sakpaas/backend/v1/controller/LocationController.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/test/java/de/sakpaas/backend/IntegrationTest.java
  src/test/java/de/sakpaas/backend/RepositoryTest.java
  src/test/java/de/sakpaas/backend/model/OccupancyTest.java
  src/test/java/de/sakpaas/backend/service/LocationServiceTest.java
  src/test/java/de/sakpaas/backend/service/OccupancyRepositoryTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointAddFavoriteByLocationIdTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointGetLocationByIdTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointGetLocationsByCoordinatesTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointRemoveFavoriteByLocationIdTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointSearchLocationsTest.java
Labels: enhancement

#169 TINF-394: OccupancyService.checkReportLimit()
  src/main/java/de/sakpaas/backend/exception/TooManyRequestsException.java
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/main/java/de/sakpaas/backend/util/OccupancyReportLimitsConfiguration.java
  src/main/resources/application.yml
  src/test/java/de/sakpaas/backend/service/OccupancyServiceTest.java
Labels: enhancement

#170 TINF-395: OccupancyService.checkReportLimit() in LocationController
  src/main/java/de/sakpaas/backend/v1/controller/LocationController.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointAddOccupancyTest.java
Labels: enhancement

#172 TINF-431: Structure for new Occupancy Calculation
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/main/resources/application.yml
  src/test/java/de/sakpaas/backend/service/OccupancyRepositoryTest.java
Labels: feature, story

#171 TINF-437: Added filter by type in SearchService
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/main/java/de/sakpaas/backend/service/SearchService.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/test/java/de/sakpaas/backend/service/SearchServiceTest.java
  src/test/java/de/sakpaas/backend/v2/controller/EndpointSearchLocationsTest.java
Labels: feature

#173 TINF-432: aggregation hour
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/test/java/de/sakpaas/backend/service/OccupancyServiceTest.java
Labels: feature, story

#175 TINF-438 liquibase implementation
  pom.xml
  src/main/resources/application.yml
  src/main/resources/db/changelog/db-changelog.json
  src/main/resources/sql/on_release.sql
  src/main/resources/sql/remove-requests.sql
Labels: feature

#174 TINF-421: historical data aggregation
  src/main/java/de/sakpaas/backend/BackendApplication.java
  src/main/java/de/sakpaas/backend/model/Occupancy.java
  src/main/java/de/sakpaas/backend/model/OccupancyHistory.java
  src/main/java/de/sakpaas/backend/model/OccupancyHistoryId.java
  src/main/java/de/sakpaas/backend/service/OccupancyHistoryRepository.java
  src/main/java/de/sakpaas/backend/service/OccupancyHistoryService.java
  src/main/java/de/sakpaas/backend/service/OccupancyRepository.java
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/main/java/de/sakpaas/backend/util/ApplicationStartupListener.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/main/resources/application.yml
  src/test/java/de/sakpaas/backend/RepositoryTest.java
  src/test/java/de/sakpaas/backend/service/OccupancyHistoryRepositoryTest.java
  src/test/java/de/sakpaas/backend/service/OccupancyHistoryServiceTest.java
Labels: feature, story

#176 TINF-434: Auswertung historischer Daten
  src/main/java/de/sakpaas/backend/model/OccupancyHistory.java
  src/main/java/de/sakpaas/backend/service/OccupancyHistoryRepository.java
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/test/java/de/sakpaas/backend/service/OccupancyHistoryRepositoryTest.java
  src/test/java/de/sakpaas/backend/service/OccupancyServiceTest.java
Labels: feature, story

#177 TINF-429: check if public holiday
  pom.xml
  src/main/java/de/sakpaas/backend/service/OccupancyHistoryService.java
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/test/java/de/sakpaas/backend/service/OccupancyHistoryServiceTest.java
  src/test/java/de/sakpaas/backend/service/OccupancyServiceTest.java
Labels: feature
