Repository SAKPaaS/backend, pull requests merged in 2020-04, with the labels that each got.

#70 Added check to only allow one database import at a time
  src/main/java/de/sakpaas/backend/service/LocationApiSearchDAS.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
Labels: bug

#74 Occupancy Lebensdauer in yaml
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/main/resources/application.yml
Labels: important

#78 Added VersionedBeanNameGenerator to Tests
  src/main/java/de/sakpaas/backend/BackendApplication.java
Labels: bug

#84 Removed redundant request Counter from Controller.
  src/main/java/de/sakpaas/backend/controller/StatusController.java
  src/main/java/de/sakpaas/backend/v1/controller/LocationController.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
Labels: duplicate

#85 Fixed import progress meters
  src/main/java/de/sakpaas/backend/service/LocationService.java
Labels: bug

#86 Added Validators to occupancy reports
  src/main/java/de/sakpaas/backend/dto/Error400Dto.java
  src/main/java/de/sakpaas/backend/util/GlobalExceptionHandler.java
  src/main/java/de/sakpaas/backend/v1/controller/LocationController.java
  src/main/java/de/sakpaas/backend/v1/dto/OccupancyReportDto.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/main/java/de/sakpaas/backend/v2/dto/OccupancyReportDto.java
Labels: bug

#88 Implement CheckStyle
  .github/workflows/linter.yaml
  codestyle.xml
  pom.xml
  src/main/java/de/sakpaas/backend/BackendApplication.java
  src/main/java/de/sakpaas/backend/controller/StatusController.java
  src/main/java/de/sakpaas/backend/dto/Error400Dto.java
  src/main/java/de/sakpaas/backend/dto/OSMResultLocationListDto.java
  src/main/java/de/sakpaas/backend/dto/OsmResultLocationListDto.java
  src/main/java/de/sakpaas/backend/dto/StatusDto.java
  src/main/java/de/sakpaas/backend/exception/UnsupportedEndpointException.java
  src/main/java/de/sakpaas/backend/http/InterceptorAppConfig.java
  src/main/java/de/sakpaas/backend/http/RequestInterceptor.java
  src/main/java/de/sakpaas/backend/model/AccumulatedOccupancy.java
  src/main/java/de/sakpaas/backend/model/Address.java
  src/main/java/de/sakpaas/backend/model/Location.java
  src/main/java/de/sakpaas/backend/model/LocationDetails.java
  src/main/java/de/sakpaas/backend/model/Occupancy.java
  src/main/java/de/sakpaas/backend/model/Presence.java
  src/main/java/de/sakpaas/backend/model/Request.java
  src/main/java/de/sakpaas/backend/service/AddressRepository.java
  src/main/java/de/sakpaas/backend/service/AddressService.java
  src/main/java/de/sakpaas/backend/service/LocationApiSearchDAS.java
  src/main/java/de/sakpaas/backend/service/LocationApiSearchDas.java
  src/main/java/de/sakpaas/backend/service/LocationDetailsRepository.java
  src/main/java/de/sakpaas/backend/service/LocationDetailsService.java
  src/main/java/de/sakpaas/backend/service/LocationRepository.java
  src/main/java/de/sakpaas/backend/service/LocationService.java
  src/main/java/de/sakpaas/backend/service/OccupancyRepository.java
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/main/java/de/sakpaas/backend/service/PresenceRepository.java
  src/main/java/de/sakpaas/backend/service/PresenceService.java
  src/main/java/de/sakpaas/backend/service/RequestService.java
  src/main/java/de/sakpaas/backend/util/GlobalExceptionHandler.java
  src/main/java/de/sakpaas/backend/util/VersionedBeanNameGenerator.java
  src/main/java/de/sakpaas/backend/v1/controller/LocationController.java
  src/main/java/de/sakpaas/backend/v1/dto/LocationDto.java
  src/main/java/de/sakpaas/backend/v1/dto/OccupancyReportDto.java
  src/main/java/de/sakpaas/backend/v1/mapper/LocationMapper.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/main/java/de/sakpaas/backend/v2/dto/LocationResultLocationDto.java
  src/main/java/de/sakpaas/backend/v2/dto/OccupancyReportDto.java
  src/main/java/de/sakpaas/backend/v2/mapper/LocationMapper.java
Labels: enhancement

#91 TINF-60: removed unused methods and variables
  src/main/java/de/sakpaas/backend/http/InterceptorAppConfig.java
  src/main/java/de/sakpaas/backend/model/Request.java
  src/main/java/de/sakpaas/backend/service/AddressService.java
  src/main/java/de/sakpaas/backend/service/LocationApiSearchDas.java
  src/main/java/de/sakpaas/backend/service/LocationDetailsService.java
  src/main/java/de/sakpaas/backend/service/LocationRepository.java
  src/main/java/de/sakpaas/backend/service/LocationService.java
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/main/java/de/sakpaas/backend/service/PresenceRepository.java
  src/main/java/de/sakpaas/backend/service/RequestRepository.java
Labels: enhancement

#96 TINF-59: Backend Deployment an neue Struktur anpassen (1/2)
  .github/workflows/development.yaml
Labels: important

#100 TINF-120: Added missing imports
  src/main/java/de/sakpaas/backend/service/LocationService.java
Labels: bug

#98 TINF-59: Added GitHub Action for integration environment
  .github/workflows/integration.yaml
Labels: enhancement

#101 TINF-122: Surpressed maven transfer progress in builds
  .github/workflows/linter.yaml
  Dockerfile
Labels: bug

#102 TINF-53: Funktionen den Klassen logisch zuordnen
  src/main/java/de/sakpaas/backend/service/AddressService.java
  src/main/java/de/sakpaas/backend/service/LocationDetailsService.java
  src/main/java/de/sakpaas/backend/service/LocationService.java
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/main/java/de/sakpaas/backend/service/OpenStreetMapService.java
  src/main/java/de/sakpaas/backend/service/UserService.java
  src/main/java/de/sakpaas/backend/util/CoordinatesUtils.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/main/java/de/sakpaas/backend/v2/dto/LocationResultLocationDto.java
Labels: enhancement

#105 TINF-55: Doppelte Konstruktor Annotation entfernt. Doku für @Data
  src/main/java/de/sakpaas/backend/model/Address.java
  src/main/java/de/sakpaas/backend/model/LocationDetails.java
Labels: enhancement

#93 TINF-78: fixed bug of depending entities when deleting locations
  pom.xml
  src/main/java/de/sakpaas/backend/dto/OsmResultLocationListDto.java
  src/main/java/de/sakpaas/backend/model/Address.java
  src/main/java/de/sakpaas/backend/model/LocationDetails.java
  src/main/java/de/sakpaas/backend/service/AddressService.java
  src/main/java/de/sakpaas/backend/service/LocationDetailsService.java
  src/main/java/de/sakpaas/backend/service/LocationService.java
  src/main/java/de/sakpaas/backend/service/OccupancyRepository.java
  src/main/java/de/sakpaas/backend/service/OpenStreetMapService.java
  src/main/java/de/sakpaas/backend/service/PresenceRepository.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/main/java/de/sakpaas/backend/v2/dto/LocationResultLocationDto.java
  src/main/java/de/sakpaas/backend/v2/dto/OccupancyReportDto.java
  src/test/java/de/sakpaas/backend/service/LocationServiceTest.java
  src/test/java/de/sakpaas/backend/service/OccupancyCalculationServiceTest.java
Labels: bug

#97 TINF-111: performance optimierung datenbankimport
  pom.xml
  src/main/java/de/sakpaas/backend/AsyncConfiguration.java
  src/main/java/de/sakpaas/backend/dto/OsmResultLocationListDto.java
  src/main/java/de/sakpaas/backend/service/LocationRepository.java
  src/main/java/de/sakpaas/backend/service/OpenStreetMapService.java
  src/main/resources/application.yml
  src/test/java/de/sakpaas/backend/service/OccupancyCalculationServiceTest.java
Labels: enhancement

#106 TINF-97: New occupany calculation
  src/main/java/de/sakpaas/backend/service/OccupancyService.java
  src/main/java/de/sakpaas/backend/util/OccupancyAccumulationConfiguration.java
  src/main/resources/application.yml
  src/test/java/de/sakpaas/backend/service/OccupancyCalculationServiceTest.java
  src/test/java/de/sakpaas/backend/service/OccupancyServiceTest.java
Labels: bug, enhancement

#108 TINF-XX: Fixed typo
  .github/workflows/integration.yaml
Labels: bug

#113 TINF-223: Lokales Nominatim gibt immer HTTP 406 zurück
  src/main/java/de/sakpaas/backend/service/LocationService.java
  src/main/resources/application.yml
Labels: bug

#115 TINF-223: Hotfix for Nominatim 406 Bug
  src/main/java/de/sakpaas/backend/service/LocationService.java
Labels: bug, important

#119 TINF-167: Endpoint zum auflisten aller Favoriten eines Users
  src/main/java/de/sakpaas/backend/v2/controller/UserController.java
  src/main/resources/application.yml
  src/test/java/de/sakpaas/backend/controller/UserControllerTest.java
Labels: enhancement

#111 TINF-159: Exception Handler
  src/main/java/de/sakpaas/backend/exception/ApplicationException.java
  src/main/java/de/sakpaas/backend/exception/ErrorAttributes.java
  src/main/java/de/sakpaas/backend/exception/InvalidLocationException.java
  src/main/java/de/sakpaas/backend/exception/UnsupportedEndpointException.java
  src/main/java/de/sakpaas/backend/util/GlobalExceptionHandler.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/test/java/de/sakpaas/backend/service/ExceptionHandler.java
Labels: enhancement

#114 TINF-155: Suche-überarbeiten
  src/main/java/de/sakpaas/backend/dto/NominatimSearchResultListDto.java
  src/main/java/de/sakpaas/backend/dto/OsmResultLocationListDto.java
  src/main/java/de/sakpaas/backend/exception/NoSearchResultsException.java
  src/main/java/de/sakpaas/backend/model/CoordinateDetails.java
  src/main/java/de/sakpaas/backend/model/SearchResultObject.java
  src/main/java/de/sakpaas/backend/service/LocationService.java
  src/main/java/de/sakpaas/backend/service/OpenStreetMapService.java
  src/main/java/de/sakpaas/backend/service/SearchMappingService.java
  src/main/java/de/sakpaas/backend/service/SearchService.java
  src/main/java/de/sakpaas/backend/util/MyConfiguration.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/main/java/de/sakpaas/backend/v2/controller/UserController.java
  src/main/java/de/sakpaas/backend/v2/dto/LocationResultLocationDto.java
  src/main/java/de/sakpaas/backend/v2/dto/SearchResultDto.java
  src/main/java/de/sakpaas/backend/v2/mapper/LocationMapper.java
  src/main/java/de/sakpaas/backend/v2/mapper/SearchResultMapper.java
  src/test/java/de/sakpaas/backend/controller/UserControllerTest.java
  src/test/java/de/sakpaas/backend/mapper/SearchResultMapperTest.java
  src/test/java/de/sakpaas/backend/service/SearchMappingServiceTest.java
Labels: enhancement

#123 TINF-275 - Anpassen der application.yml
  src/main/resources/application.yml
Labels: enhancement

#128 TINF-288: Applikation startet lokal nicht ohne Keycloak
  src/main/java/de/sakpaas/backend/exception/NoKeycloakDeploymentException.java
  src/main/java/de/sakpaas/backend/service/UserService.java
  src/main/java/de/sakpaas/backend/util/KeycloakConfiguration.java
Labels: bug, important

#133 TINF-294: Updated SearchRequest and SearchService
  src/main/java/de/sakpaas/backend/model/SearchRequest.java
  src/main/java/de/sakpaas/backend/service/SearchService.java
Labels: enhancement

#131 TINF-295: Implemented Brand Checker in Search
  src/main/java/de/sakpaas/backend/service/SearchService.java
  src/test/java/de/sakpaas/backend/service/SearchServiceTest.java
Labels: enhancement

#135 TINF-280 + TINF-281 + TINF-282: GitHub Action for Integration
  .github/workflows/development.yaml
  .github/workflows/integration-scale-down.yaml
  .github/workflows/integration.yaml
  .github/workflows/release.yml
Labels: enhancement

#136 TINF-165 + TINF-166: Favorite Endpoint
  src/main/java/de/sakpaas/backend/service/FavoriteRepository.java
  src/main/java/de/sakpaas/backend/service/FavoriteService.java
  src/main/java/de/sakpaas/backend/v2/controller/UserController.java
Labels: enhancement

#138 TINF-282: Fixed broken GitHub-Action condition and kustomize script
  .github/workflows/integration-scale-down.yaml
  .github/workflows/integration.yaml
Labels: bug

#142 TINF-243: Story update via branch
  .github/workflows/development.yaml
  .github/workflows/integration-scale-down.yaml
  .github/workflows/integration.yaml
  .github/workflows/release.yml
  src/main/java/de/sakpaas/backend/service/FavoriteRepository.java
  src/main/java/de/sakpaas/backend/service/FavoriteService.java
  src/main/java/de/sakpaas/backend/v2/controller/UserController.java
Labels: help wanted

#129 TINF-251: Anpassen der Datentypen im Datenbankmodell
  src/main/java/de/sakpaas/backend/model/Address.java
  src/main/java/de/sakpaas/backend/model/Location.java
  src/main/java/de/sakpaas/backend/model/LocationDetails.java
  src/main/java/de/sakpaas/backend/model/Occupancy.java
  src/main/resources/on_release.sql
  src/test/java/de/sakpaas/backend/service/AddressServiceTest.java
Labels: enhancement

#146 TINF-303: create request
  src/main/java/de/sakpaas/backend/model/Address.java
  src/main/java/de/sakpaas/backend/model/Location.java
  src/main/java/de/sakpaas/backend/model/LocationDetails.java
  src/main/java/de/sakpaas/backend/model/Occupancy.java
  src/main/java/de/sakpaas/backend/service/LocationRepository.java
  src/main/java/de/sakpaas/backend/service/LocationService.java
  src/main/java/de/sakpaas/backend/service/SearchService.java
  src/main/java/de/sakpaas/backend/v2/controller/LocationController.java
  src/main/resources/application.yml
  src/main/resources/on_release.sql
  src/test/java/de/sakpaas/backend/service/AddressServiceTest.java
  src/test/java/de/sakpaas/backend/service/LocationRepositoryTest.java
  src/test/java/de/sakpaas/backend/service/LocationServiceTest.java
  src/test/java/de/sakpaas/backend/service/SearchServiceTest.java
Labels: enhancement

#132 TINF-297: GetByCoordinates
  src/main/java/de/sakpaas/backend/service/SearchService.java
  src/test/java/de/sakpaas/backend/service/SearchServiceIntegrationTest.java
  src/test/java/de/sakpaas/backend/service/SearchServiceTest.java
Labels: enhancement

#134 TINF-296 + TINF-272: Implementieren des Nominatim Requests + Encoding der URL
  src/main/java/de/sakpaas/backend/service/SearchMappingService.java
  src/main/java/de/sakpaas/backend/service/SearchService.java
  src/test/java/de/sakpaas/backend/service/SearchMappingServiceTest.java
  src/test/java/de/sakpaas/backend/service/SearchServiceTest.java
Labels: enhancement
